services:
  postgres:
    image: postgres:18-alpine
    container_name: pg_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sc_stats
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  pgdata:
    name: 'sc_stats_db'
